cart/urls.py
from django.conf.urls import url
from . import views


app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>[\d]+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>[\d]+)/$', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'cart/', include('cart.urls', namespace='cart')),
    url(r'orders/', include('order.urls', namespace='orders')),
    url(r'^', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.conf.urls import url
from . import views


app_name = 'order'


urlpatterns = [
    url(r'^created/$', views.order_create, name='order_create'),
]

shop/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'shop'

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>[\d]+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

order/models.py
from django.db import models
from shop.models import Product


# Create your models here.
class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='item', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'{self.id}'

    def get_cost(self):
        return self.price * self.quantity

shop/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='product/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForms(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='数量')
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

order/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForms


# Create your views here.
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForms(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForms(
            initial={'quantity': item['quantity'],
                     'update': True}
        )
    return render(request, 'cart/detail.html', {'cart': cart})

order/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart
from .task import order_created


# Create your views here.
def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'], price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()
            # order_created.delay(order.id)
            return render(request, 'orders/order/created.html', {'order': order})
    else:
        form = OrderCreateForm()
    return render(request, 'orders/order/create.html', {'cart': cart, 'form': form})

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForms


# Create your views here.
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_porduct_form = CartAddProductForms()
    return render(request, 'shop/product/detail.html', {'product': product, 'cart_product_form': cart_porduct_form})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    Your shopping cart
{% endblock %}

{% block content %}
    <h3>购物车列表</h3>
    {% for item in cart %}
        <div class="panel panel-info row">
            {% with product=item.product %}
                <div class="col-lg-3">
                    <a class="thumbnail" style="margin: 10px 0;" href="{{ product.get_absolute_url }}">
                        <img height="180" src="{% if product.image %}{{ product.image.url }}{% else %}https://ss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=1234473017,3789785852&fm=27&gp=0.jpg{% endif %}">
                    </a>
                </div>
                <div class="col-lg-8 m-t-10">
                    <div class="text-muted  m-t-10">商品名称：{{ product.name }}</div>
                    <form class="jd-form-input  m-t-10" action="{% url "cart:cart_add" product.id %}" method="post">
                        <label class="text-muted"  style="font-weight: bold;" for="id_quantity">商品数量:</label>
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.update }}
                        <input type="submit" class="btn-jd" value="修改数量">
                        {% csrf_token %}
                    </form>
                    <div class="row">
                        <div class="text-muted col-lg-12  m-t-10">当前商品单价：￥{{ item.price }}</div>
                        <div class="text-muted col-lg-8   m-t-10">当前商品总价：￥{{ item.total_price }}</div>
                        <a class="text-muted col-lg-4" style="text-align: right;" href="{% url "cart:cart_remove" product.id%}"><button type="button" class="btn btn-danger">清空</button></a>
                    </div>
                </div>
            {% endwith %}
        </div>
    {% endfor %}
    <div class="row">
        <span class="col-lg-6">总计：<span class="text-danger">￥{{ cart.get_total_price }}</span></span>
        <p class="text-right col-lg-6">
            <a href="{% url "shop:product_list" %}" class="btn btn-primary">继续购物</a>
            <a href="{% url "order:order_create" %}" class="btn btn-info">提交订单</a>
        </p>
    </div>
{% endblock %}

order/templates/orders/order/create.html
{% extends "shop/base.html" %}

{% block title %}
Checkout
{% endblock %}

{% block content %}
    <h1>Checkout</h1>
    <div class="order-info">
        <h3>Your order</h3>
        <ul>
            {% for item in cart %}
                <li>
                    {{ item.quantity }} * {{ item.product.name }}
                    <span>${{ item.total_price }}</span>
                </li>
            {% endfor %}
        </ul>
        <p> Total:${{ cart.get_total_price }}</p>
    </div>
    <form action="." method="post" class="order-form">
        <div class="row">
            <div class="form-group col-lg-4">
                <label for="exampleInputEmail1">姓</label>
                <input type="text" class="form-control" id="first_name" name="first_name" placeholder="姓">
            </div>
        </div>
        <div class="row">
            <div class="form-group col-lg-4">
                <label for="exampleInputEmail1">名</label>
                <input type="text" class="form-control" id="last_name" name="last_name" placeholder="名">
            </div>
        </div>
        <div class="row">
            <div class="form-group col-lg-4">
                <label for="exampleInputEmail1">地址</label>
                <input type="text" class="form-control" id="address" name="address" placeholder="地址">
            </div>
        </div>
        <div class="row">
            <div class="form-group col-lg-4">
                <label for="exampleInputEmail1">邮编</label>
                <input type="number" class="form-control" id="postal_code" name="postal_code" placeholder="邮编">
            </div>
        </div>
        <div class="row">
            <div class="form-group col-lg-4">
                <label for="exampleInputEmail1">城市</label>
                <input type="text" class="form-control" id="city" name="city" placeholder="城市">
            </div>
        </div>
        <div class="row">
            <div class="form-group col-lg-4">
                <label for="exampleInputEmail1">邮箱</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="邮箱">
            </div>
        </div>
        <p><input type="submit" value="提交订单"></p>
        {% csrf_token %}

    </form>
{% endblock %}

order/templates/orders/order/created.html
{% extends "shop/base.html" %}

{% block title %}
Thank you
{% endblock %}

{% block content %}
    <h1> Thank you</h1>
    <p>
        Your order has been successfully completed, you order number is <strong>{{ order.id }}</strong>
    </p>
{% endblock %}

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} My shop{% endblock %}</title>
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style>
        .f-12 {
            font-size:12px;
        }
        .f-16 {
            font-size:16px;
        }
        .f-18 {
            font-size:18px;
        }
        .f-20 {
            font-size:20px;
        }
        .f-22 {
            font-size:22px;
        }
        .f-24 {
            font-size:24px;
        }
        .f-26 {
            font-size:26px;
        }
        .f-28 {
            font-size:28px;
        }
        .f-34 {
            font-size:34px;
        }
        body {
           font: 700 16px Arial,"microsoft yahei";
        }
        .f-bold {
            font-weight: bold;
        }

        .btn-jd {
            height: 46px;
            line-height: 46px;
            padding: 0 26px;
            font-size: 18px;
            font-family: "microsoft yahei";
            background-color: #df3033;
            color: #fff;
            display: inline-block;
            text-align: center;
            vertical-align: middle;
            cursor: pointer;
            outline: none;
            border: none;
        }

        .btn-jd:nth-of-type(2) {
            background-color: #1185f6;
        }

        .input-jd {
            display: block;
            width: 43px;
            height: 42px;
            line-height: 42px;
            border: none;
            border: 0;
            text-align: center;
        }

        .jd-form-input #id_quantity {
            width: 58px;
            height: 44px;
            overflow: hidden;
            border: 1px solid #ccc;
            margin:0 10px;
            text-align: center;
            text-align-last: center;
            color: #777777;
            font-weight: 400;
        }

        .jd-form-input label {
            font-size:14px;
            color: #777;
            font-weight: 400;
        }

        .fuck p{
            text-indent: 20px;
            margin: 10px 0 0;
        }
        .m-10 {
            margin: 10px 0;
        }
        .m-b-10 {
            margin: 0 0 10px;
        }
        .m-t-10 {
            margin: 10px 0 0px;
        }
        .panel-info:hover {
            background:#fff4e8;
        }
    </style>
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Shop</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse navbar-left">
          <ul class="nav navbar-nav">
            <li {% if not category %} class="active"{% endif %}>
                <a href="{% url "shop:product_list" %}">所有种类</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %} class="active"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
          </ul>
        </div>
          <div class="nav navbar-nav navbar-right">
              <div class="alert alert-dark" role="alert">
                <ul class="navbar-nav bd-navbar-nav flex-row">
                   {% with total_items=cart|length %}
                        {% if cart|length%}
                            <span class="text-muted">购物车:</span>
                            <a href="{% url "cart:cart_detail" %}" target="_blank">
                                <span class="text-success">共 {{ total_items }} 件商品</span>
                                <span class="badge">${{ cart.get_total_price }}</span>
                            </a>
                        {% else %}
                            <div class="text-warning">购物车为空</div>
                        {% endif %}
                    {% endwith %}
                </ul>
            </div>
          </div>
      </div>
    </nav>
    <div class="container" style="padding-top: 50px;">

        {% block content %}
        {% endblock %}
    </div>
<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if product %}{{ product.category }}{% else %}Product{% endif %}
{% endblock %}

{% block content %}
    <div class="product-detail row text-left">
        <div class="col-lg-6" style="margin-top: 10px;">
            <img class="img-responsive" src={% if product.image %}{{ product.image.url }}{% else %}https://ss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=1234473017,3789785852&fm=27&gp=0.jpg{% endif %}>
        </div>
        <div class="col-lg-6">
            <h4>物品名称：{{ product.name }}</h4>
            <h5><a href="{{ product.categor.get_absolute_url }}">商品类别：{{ product.category }}</a> </h5>
            <p class="price h5 text-muted">惊爆价：<em class="f-34" style="color: #e4393c;font-style: normal;"><span class="f-bold f-18">￥</span>{{ product.price }}</em></p>
            <form class="form-group jd-form-input" action="{% url "cart:cart_add" product.id %}" method="post">
                {{ cart_product_form }}
                {% csrf_token %}
                <input type="submit" class="btn-jd" value="加入购物车" />
            </form>
            <div class="alert alert-danger" role="alert">
                <p>商品描述：</p>
                <div class="text-muted fuck">{{ product.description|linebreaks }}</div>
            </div>
            <p class="text-muted">温馨提示: 不支持7天无理由退货</p>
        </div>
    </div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Procucts{% endif %}
{% endblock %}

{% block content %}
    <div id="main" class="product-list row">
        <h1>{% if category %}{{ category.name }}{% else %}Product{% endif %}</h1>
        {% for product in products %}
            <div class="item col-xs-6 col-lg-4">
                <a href="{{ product.get_absolute_url }}" target="_blank">
                    <img class="img-thumbnail" height="180" alt="Responsive image" src="{% if product.image %}{{ product.image.url }}{% else %}https://ss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=1234473017,3789785852&fm=27&gp=0.jpg{% endif %}">
                </a>
                <p class="text-center">
                    <a target="_blank" href="{{ product.get_absolute_url }}">
                        <h5 class="text-center"><span class="text-info">{{ product.name }}</span> <span class="text-danger">${{ product.price }}</span></h5>
                    </a>
                </p>
            </div>
        {% endfor %}
    </div>
{% endblock %}